---
name: task-releaser
description: |
  Action to release a Tekton Task packaged as a Helm-Chart. The release is based on the Chart
  (Chart.yaml) version and the current Git tag (shared via `GITHUB_REF_NAME`), the following
  artifacts are release:

   - Tekton Task resource (`.yaml`)
   - Tekton Task Bundle container-image (OCI)
   - Helm-Chart package (`.tgz`)
   - Helm-Chart container-image (OCI)
inputs:
  chart_image_tag_suffix:
    description: |
      Helm-Chart OCI container-image tag suffix
    default: "-chart"
    required: false
  cli_version:
    description: |
      Tekton CLI (`tkn`) version
    default: latest
    required: false
  helm_version:
    description: |
      Helm CLI (`helm`) version
    default: latest
    required: false
  crane_version:
    description: |
      go-containerregistry/crane version
    default: v0.13.0
    required: false
runs:
  using: composite
  steps:
    - uses: azure/setup-helm@v3
      with:
        version: ${{ inputs.helm_version }}

    - uses: imjasonh/setup-crane@v0.3
      with:
        version: ${{ inputs.crane_version }}

    - uses: otaviof/setup-tekton-cli@main
      with:
        version: ${{ inputs.cli_version }}

    - shell: bash
      run: ${{ github.action_path }}/probe.sh

    - shell: bash
      working-directory: ${{ github.action_path }}
      run: make registry-start

    - shell: bash
      env:
        INPUT_CHART_IMAGE_TAG_SUFFIX: ${{ inputs.chart_image_tag_suffix }}
      run: ${{ github.action_path }}/release.sh

    - shell: bash
      working-directory: ${{ github.action_path }}
      run: make registry-stop
