---
name: task-releaser
description: |
  Releases a Tekton Task...
inputs:
  chart_releaser_version:
    default: v1.5.0
    description: Version of helm/chart-releaser (cr)
    required: false
runs:
  using: composite
  steps:
    - shell: bash
      env:
        INPUT_CHART_RELEASER_VERSION: ${{ inputs.chart_releaser_version }}
      run: sudo -E ${{ github.action_path }}/install-chart-releaser.sh

    - shell: bash
      run: ${{ github.action_path }}/probe.sh

    - shell: bash
      run: ${{ github.action_path }}/task-releaser.sh